// user
export const SAVE_USER_EMAIL = "SAVE_USER_EMAIL";
export const SAVE_PASSWORD_CHECK = "SAVE_CHECK_PASSWORD";

// 구매 -공연목적
export const SAVE_GROUP_NAME = "SAVE_GROUP_NAME";
export const SAVE_ABOUT_GROUP = "SAVE_ABOUT_GROUP";
export const SAVE_PLANNED_CONTENTS = "SAVE_PLANNED_CONTENTS";
export const SAVE_SCHEDULE = "SAVE_SCHEDULE";
export const SAVE_NUMBER = "SAVE_NUMBER"; // 공연회차
export const SAVE_PLACE = "SAVE_PLACE";
export const SAVE_PRICE = "SAVE_PRICE";
export const SAVE_CHANGE_SCENARIO = "SAVE_CHANGE_SCENARIO";
export const SAVE_RANGE_OF_CHANGE = "SAVE_RANGE_OF_CHANGE";
export const SAVE_REQUIRED_MATERIALS = "SAVE_REQUIRED_MATERIALS";
export const SAVE_SELECT_MATERIALS = "SAVE_SELECT_MATERIALS";
export const SAVE_CAST_MEMBERS = "SAVE_CAST_MEMBERS";
export const SAVE_STAFF_MEMBERS = "SAVE_STAFF_MEMBERS";
export const SAVE_NAME = "SAVE_NAME";
export const SAVE_PHONE = "SAVE_PHONE";
export const SAVE_COMMENT = "SAVE_COMMENT";
